- id: helm-readme-generator
  name: Generate Helm Charts documentation using Bitnami generator
  description: This hooks generates the documentation for Helm Charts using Bitnami generator.
  entry: "node bin/index.js"
  language: node
